CREATE OR REPLACE PROCEDURE FINDGREATEST(NUM1 IN NUMBER,NUM2 IN NUMBER,NUM3 IN NUMBER,RESULT OUT NUMBER)AS
BEGIN
IF NUM1>=NUM2 AND NUM1>=NUM3 THEN
RESULT:=NUM1;
ELSIF
NUM2>=NUM1 AND NUM2>=NUM3 THEN
RESULT:=NUM2;
ELSE
RESULT:=NUM3;
END IF;
END FINDGREATEST;