DECLARE
greatest_num NUMBER;
BEGIN
FINDGREATEST(10,25,15,greatest_num);
DBMS_OUTPUT.PUT_LINE('THE GREATEST NUMBER IS:'||greatest_num);
END;


//DROPPING A PROCEDURE
DROP PROCEDURE FINDGREATEST;
PROCEDURE DROPPED



