CREATE OR REPLACE TRIGGER T12
BEFORE INSERT OR UPDATE ON EMPLOY
FOR EACH ROW
DECLARE
   CTR NUMBER;
BEGIN
   SELECT COUNT(*)
   INTO CTR
   FROM EMPLOY
   WHERE ENO=:NEW.ENO;
   IF CTR>0 THEN
      RAISE_APPLICATION_ERROR(-20003,'DUPLICATION NOT POSSIBLE');
END IF;
END;
